/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negocio.Imagem;
import Negocio.Localizacao;
import Negocio.Texto;
import javax.swing.JOptionPane;

/**
 *
 * @author Jadson Nobre
 */
public class CadConteudo extends javax.swing.JFrame {
    /**
     * Creates new form CadConteudo
     */
    public CadConteudo() {
        initComponents();
        text_link.setEnabled(false);
        text_link.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        label_cadProduto = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        text_nome = new javax.swing.JTextField();
        label_assunto = new javax.swing.JLabel();
        text_assunto = new javax.swing.JTextField();
        label_size = new javax.swing.JLabel();
        text_coordX = new javax.swing.JTextField();
        label_coordX = new javax.swing.JLabel();
        label_coordY = new javax.swing.JLabel();
        text_coordY = new javax.swing.JTextField();
        text_size = new javax.swing.JTextField();
        label_localizacao = new javax.swing.JLabel();
        check_link = new javax.swing.JCheckBox();
        text_link = new javax.swing.JTextField();
        button_texto = new javax.swing.JRadioButton();
        button_imagem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 102));

        label_cadProduto.setFont(new java.awt.Font("Script MT Bold", 2, 24)); // NOI18N
        label_cadProduto.setForeground(new java.awt.Color(51, 102, 255));
        label_cadProduto.setText("Cadastro de Conteúdo");

        label_nome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_nome.setText("Nome");

        text_nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_nome.setToolTipText("");

        label_assunto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_assunto.setText("Assunto");

        text_assunto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_assunto.setToolTipText("");

        label_size.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_size.setText("Tamanho");

        text_coordX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_coordX.setToolTipText("");

        label_coordX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_coordX.setText("Coord X : ");

        label_coordY.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_coordY.setText("Coord Y : ");

        text_coordY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_coordY.setToolTipText("");

        text_size.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_size.setToolTipText("");

        label_localizacao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_localizacao.setText("Localização");

        check_link.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check_link.setText("Link : ");
        check_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_linkActionPerformed(evt);
            }
        });

        text_link.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_link.setToolTipText("");

        button_texto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_texto.setText("Texto");
        button_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_textoActionPerformed(evt);
            }
        });

        button_imagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_imagem.setText("Imagem");
        button_imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_imagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(label_nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(label_assunto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(label_size))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(label_localizacao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_coordX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_coordX, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_coordY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_coordY, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_cadProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_nome)
                                .addComponent(text_assunto)
                                .addComponent(text_size, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(check_link)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(text_link))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_texto)
                .addGap(18, 18, 18)
                .addComponent(button_imagem)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_cadProduto)
                .addGap(18, 18, 18)
                .addComponent(label_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_assunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_assunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_size)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_localizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_coordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_coordX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_coordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_coordY))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check_link)
                            .addComponent(text_link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_imagem)
                            .addComponent(button_texto))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_linkActionPerformed
        // TODO add your handling code here:
        if(check_link.isSelected()){
            text_link.setText("");
            text_link.setEnabled(true);
        }
        else{
            text_link.setText("");
            text_link.setEnabled(false);
        }         
    }//GEN-LAST:event_check_linkActionPerformed

    private void button_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_textoActionPerformed
        // TODO add your handling code here:
        //Instanciado Objeto
        Texto texto = new Texto();
        texto.setNome(text_nome.getText());
        texto.setAssunto(text_assunto.getText());
        texto.setSize(Float.parseFloat(text_size.getText()));
        
        Localizacao pos = new Localizacao(Integer.parseInt(text_coordX.getText()), Integer.parseInt(text_coordY.getText()));
        
        texto.setPos(pos);
        
        if(check_link.isSelected()){
            texto.setLink(text_link.getText());
        }
            
        
        CadTexto cadTexto = new CadTexto(texto);
        cadTexto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_textoActionPerformed

    private void button_imagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_imagemActionPerformed
        // TODO add your handling code here:
        //Instanciado Objeto
        Imagem imagem = new Imagem();
        imagem.setNome(text_nome.getText());
        imagem.setAssunto(text_assunto.getText());
        imagem.setSize(Float.parseFloat(text_size.getText()));
        
        Localizacao pos = new Localizacao(Integer.parseInt(text_coordX.getText()), Integer.parseInt(text_coordY.getText()));
        
        imagem.setPos(pos);
        
        if(check_link.isSelected()){
            imagem.setLink(text_link.getText());
        }
        
        CadImagem cadImagem = new CadImagem(imagem);
        cadImagem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_imagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadConteudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton button_imagem;
    private javax.swing.JRadioButton button_texto;
    private javax.swing.JCheckBox check_link;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_assunto;
    private javax.swing.JLabel label_cadProduto;
    private javax.swing.JLabel label_coordX;
    private javax.swing.JLabel label_coordY;
    private javax.swing.JLabel label_localizacao;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_size;
    private javax.swing.JTextField text_assunto;
    private javax.swing.JTextField text_coordX;
    private javax.swing.JTextField text_coordY;
    private javax.swing.JTextField text_link;
    private javax.swing.JTextField text_nome;
    private javax.swing.JTextField text_size;
    // End of variables declaration//GEN-END:variables
}
